name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Compile with Docker
        run: |
          docker run --rm -v "$(pwd)":/code \
          --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
          --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
          cosmwasm/workspace-optimizer:0.14.0
          tar -zcvf elys-bindings-${{  github.ref_name }}.tar.gz artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: elys-bindings-${{  github.ref_name }}.tar.gz

      - name: Deploy to TestNet
        run: |
          ELYSD=/tmp/elysd
          NODE=https://rpc.testnet.elys.network:443
          URL=https://github.com/elys-network/elys/releases/download/v0.24.0/elysd-v0.24.0-linux-amd64
          wget $URL -O $ELYSD
          chmod +x $ELYSD
          echo ${{ secrets.KEY_MNEMONIC }} | $ELYSD keys add contract-initiator --recover --keyring-backend test
          OPTIONS="--from contract-initiator --keyring-backend test --gas auto --gas-adjustment=1.3 --fees 100000uelys --broadcast-mode sync --node $NODE --chain-id elystestnet-1 --yes"
          $ELYSD tx wasm store artifacts/account_history_contract.wasm $OPTIONS
          $ELYSD tx wasm store artifacts/financial_snapshot_contract.wasm $OPTIONS
          $ELYSD tx wasm store artifacts/trade_shield_contract.wasm $OPTIONS
