name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Compile with Docker
        run: |
          docker run --rm -v "$(pwd)":/code \
          --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
          --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
          cosmwasm/workspace-optimizer:0.14.0
          tar -zcvf elys-bindings-${{  github.ref_name }}.tar.gz artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: elys-bindings-${{  github.ref_name }}.tar.gz
