name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
  
      - name: Compile with Docker
        run: |
          # build wasm files
          ./scripts/build.sh

          # compress artifacts
          tar -zcvf elys-bindings-${{  github.ref_name }}.tar.gz artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: elys-bindings-${{  github.ref_name }}.tar.gz

      - name: Deploy to TestNet
        run: |
          # deploy
          ./scripts/deploy.sh "${{ secrets.KEY_MNEMONIC }}"

      - name: Test Queries
        run: |
          # set user address
          USER_ADDRESS=elys1dty5tjwtg55vqsxn2k0nup6my50zdpcjqyv0gy

          # add path
          export PATH=/tmp:$PATH

          # run the scripts/queries.sh script
          ./scripts/queries.sh $USER_ADDRESS
