name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Compile with Docker
        run: |
          # build wasm files
          ./scripts/build.sh

          # compress artifacts
          tar -zcvf elys-bindings-${{  github.ref_name }}.tar.gz artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: elys-bindings-${{  github.ref_name }}.tar.gz

      - name: Deploy to TestNet
        run: |
          # set key name
          NAME=contract-initiator

          # recover key
          echo ${{ secrets.KEY_MNEMONIC }} | elysd keys add $NAME --recover --keyring-backend test

          # deploy
          ./scripts/deploy.sh

      - name: Test Queries
        run: |
          # set user address
          USER_ADDRESS=elys1dty5tjwtg55vqsxn2k0nup6my50zdpcjqyv0gy

          # add path
          export PATH=/tmp:$PATH

          # run the scripts/queries.sh script
          ./scripts/queries.sh $USER_ADDRESS
