name: Rust Test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build and test
        run: |
          export VERSION="0.0.0"
          cargo build --verbose
          cargo test --verbose
        working-directory: .
